CREATE TABLE ITEMS(
	ID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL
);

INSERT INTO ITEMS VALUES
(1, 'Item1', 30.00),
(2, 'Item2', 50.00),
(3, 'Item3', 100.00),
(4, 'Item4', 320.00),
(5, 'Item5', 230.00);

SELECT * FROM ITEMS;

CREATE TABLE ITEM_CHANGES(
	CHANGE_ID INT PRIMARY KEY AUTO_INCREMENT,
    ITEM_ID INT,
    CHANGE_TYPE VARCHAR(10),
    CHANGE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID)
);

UPDATE ITEMS SET NAME = 'Mouse' WHERE ID = 3;
SELECT * FROM ITEM_CHANGES;
    
DELIMITER //
CREATE TRIGGER UPDATE_ITEMS_TRIGGER
AFTER UPDATE
ON ITEMS
FOR EACH ROW
BEGIN
	INSERT INTO ITEM_CHANGES (ITEM_ID, CHANGE_TYPE)
    VALUES(NEW.ID, 'UPDATE');
END;
//
DELIMITER ;

SELECT * FROM ITEMS;
SELECT * FROM ITEM_CHANGES;

