use rev_datanalytics;

SELECT * FROM EMPLOYEE;

SELECT ENAME FROM EMPLOYEE 
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEE);

SELECT ENAME, SALARY 
FROM EMPLOYEE
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE);

CREATE TABLE departments (
    department_id INT PRIMARY KEY,
    department_name VARCHAR(50)
);
 
CREATE TABLE workers (
    w_id INT PRIMARY KEY,
    w_name VARCHAR(50),
    department_id INT,
    FOREIGN KEY (department_id) REFERENCES departments(department_id)
);

INSERT INTO departments (department_id, department_name) VALUES
(1, 'Sales'),
(2, 'Marketing'),
(3, 'HR');

INSERT INTO departments (department_id, department_name) VALUES
(4, 'Training');
 
INSERT INTO workers (w_id, w_name, department_id) VALUES
(101, 'Alice', 1),
(102, 'Bob', 1),
(103, 'Charlie', 2),
(104, 'Diana', 3);

INSERT INTO workers (w_id, w_name, department_id) VALUES
(105, 'John', 1);

SELECT * FROM workers
WHERE Department_id = (SELECT Department_id FROM departments
WHERE department_name = 'Sales');

--  
SELECT W_NAME AS EMPLOYEES,
(SELECT DEPARTMENT_NAME FROM DEPARTMENTS
WHERE DEPARTMENTS.DEPARTMENT_ID = WORKERS.DEPARTMENT_ID) 
AS DEPARTMENT_NAME
FROM WORKERS;

-- FIND WORKERS
SELECT W_NAME
FROM WORKERS
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID 
						FROM WORKERS
						GROUP BY DEPARTMENT_ID
						HAVING COUNT(*) > 1);
                        
-- FIND DEPARTMENTS THAT HAVE AT LEAST ONE EMPLOYEE
SELECT * FROM DEPARTMENTS D
WHERE EXISTS (
SELECT 1 FROM WORKERS W
WHERE W.DEPARTMENT_ID = D.DEPARTMENT_ID
);
 
-- FIND DEPARTMENTS THAT DO NOT HAVE ANY EMPLOYEES 
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS D
WHERE NOT EXISTS (SELECT 1
FROM WORKERS W 
WHERE W.DEPARTMENT_ID = D.DEPARTMENT_ID); 

-- FIND DEPARTMENTS WHERE THE AVG EMPLOYEE ID IS GREATER THAN 102
SELECT DEPARTMENT_NAME FROM DEPARTMENTS
WHERE EXISTS (SELECT DEPARTMENT_ID
FROM WORKERS
GROUP BY DEPARTMENT_ID
HAVING AVG(W_ID) > 102);

-- ANOTHER WAY, BUT IT IS WRONG. 
SELECT DEPARTMENT_ID FROM DEPARTMENTS D
WHERE DEPARTMENT_ID > (SELECT AVG(W_ID)
FROM WORKERS W
WHERE W.DEPARTMENT_ID = D.DEPARTMENT_ID);




 
