CREATE TABLE JSON_SAMPLE(
	ID INT PRIMARY KEY,
    PROFILE JSON
);

INSERT INTO JSON_SAMPLE VALUES
(1, '{"name": "Alice", "skills": ["SQL", "Python"]}');

SELECT JSON_EXTRACT(PROFILE, '$.skills[0]') 
FROM JSON_SAMPLE;